notifications:
  email: false

git:
  depth: 3

language: php
sudo: false

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6

env:
  - DB=sqlite
  - DB=postgres

matrix:
  fast_finish: true

before_script:
  - composer install
  - npm install

script:
  - ./node_modules/.bin/jshint assets/js/{core,components}
  - ./vendor/bin/phpunit -c tests/units.$DB.xml
  - ./vendor/bin/phpunit tests/configtest
